In [1]:
import pandas as pd

In [2]:
# Load the SMS Spam Collection dataset into a pandas DataFrame
# We must specify encoding='latin-1' to handle the non-standard characters present in this specific text file
df=pd.read_csv('spam.csv',encoding='latin-1')

In [3]:
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

### Initial Data Cleaning

In [4]:
# Isolate the target (v1) and the feature (v2) columns, dropping the unnamed NaN columns
df=df[['v1','v2']]
# Rename columns
df.columns=['label','message']

In [5]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

### Checking for missing values and duplicates

In [6]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(403)

#### Dropping Duplicates and Checking Class Balance

In [8]:
df=df.drop_duplicates(keep='first')

df['label'].value_counts()

label
ham     4516
spam     653
Name: count, dtype: int64

#### Lowercasing massage column

In [9]:
df.loc[:,'message']=df['message'].str.lower()

#### Removing Punctuaion

In [10]:
import re
# Use regular expressions to remove all punctuation
# r'[^\w\s]' matches anything that is NOT an alphanumeric character (\w) or whitespace (\s)

# re.sub(pattern, replacement, text)
# This is a regex function that means: "search through text, find anything matching pattern, 
# and replace each match with replacement.

df['message']=df['message'].apply(lambda x: re.sub(r'[^\w\s]','',x))

In [11]:
df.head()

  label                                            message
0   ham  go until jurong point crazy available only in ...
1   ham                            ok lar joking wif u oni
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham        u dun say so early hor u c already then say
4   ham  nah i dont think he goes to usf he lives aroun...

#### Tokenization
* Machine learning models cannot read continuous sentences; they need text broken down into smaller, discrete units. Tokenization is the process of splitting a continuous string of text into a list of individual words (or tokens).

For example, the message `"win free tickets"` becomes the list `['win', 'free', 'tickets']`.

We will use the Natural Language Toolkit `(nltk)` library to tokenize our messages, transforming each string into a structured list of words that our algorithms can eventually count and analyze.

In [12]:
from nltk.tokenize import word_tokenize
# Apply the word_tokenize function to split each message into a list of individual words
df['tokens']=df['message'].apply(word_tokenize)
# Display tokens
print(df[['message','tokens']].head())

                                             message  \
0  go until jurong point crazy available only in ...
1                            ok lar joking wif u oni
2  free entry in 2 a wkly comp to win fa cup fina...
3        u dun say so early hor u c already then say
4  nah i dont think he goes to usf he lives aroun...

                                              tokens
0  [go, until, jurong, point, crazy, available, o...
1                     [ok, lar, joking, wif, u, oni]
2  [free, entry, in, 2, a, wkly, comp, to, win, f...
3  [u, dun, say, so, early, hor, u, c, already, t...
4  [nah, i, dont, think, he, goes, to, usf, he, l...